sonar.projectKey=Deepak-pra_Production-grade-cicd
sonar.organization=deepak-pra
sonar.projectName=Production-grade-cicd (Node)

sonar.sources=src
sonar.tests=__tests__

sonar.exclusions=node_modules/**,coverage/**,dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info