name: Test Pipeline

on:
    push:
        branches: dev

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
          - name: Code checkout
            uses: actions/checkout@v4

          - name: Setup Python
            uses: actions/setup-python@v5
            with:
                python-version: '3.11'  
